### ISSUE TITLE
When a file is re-uploaded after trashing, the trashed message is not removed.

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/widget-image#183]
When a file is deleted from trash, a message is shown: "The selected image has been moved to Trash" as per https://github.com/Rise-Vision/widget-image/issues/180

If a new file is re-uploaded to storage and it has the same file name, the image appears but the trash message does not go away.
![moved-to-trash-overlay](https://user-images.githubusercontent.com/1511535/46027809-beaa0c00-c0bc-11e8-9f3d-825a3f57d961.png)

### Steps to reproduce

 - Upload a file to storage.
 - Run that file on a presentation using the Image Widget (single image).
 - Move the file to trash.
 - Create a different image with the same file name on your machine.
 - Upload the file to storage

**Comment by stulees** [comment]
Fixed with #184 . A fix to Local Storage module  is also required. This Image widget fix was validated with a staged version of Local Storage module [here](https://storage.googleapis.com/install-versions.risevision.com/staging/local-storage/2018.10.03.16.24/local-storage.exe). Until this version 
 of Local Storage is rolled out in Electron player, a re-added image will not appear. @tejohnso FYI
