### ISSUE TITLE
Image rotated 90 degrees not appearing as rotated in Presentation

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/widget-image#19]
Take a look at the image here, https://storage.googleapis.com/risemedialibrary-30007b45-3df0-4c7b-9f7f-7d8ce6443013/Images%2Ffall1_digital_0021r%20(2).jpg.

It appears such that the persons head is rotated 90 degrees, which is how it should appear. That same image in a Presentation does not respect that rotation. Instead it appears with no rotation as shown here, http://www.screencast.com/t/0zC0KGexu

Presentation, http://rva.risevision.com/#/PRESENTATION_MANAGE/id=54dde645-a829-4e85-9aac-b8046ce42abf?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

Chrome v. 44.0.2403.157

**Comment by donnapep** [comment]
This photo was likely taken sideways on an iPhone. There's a thing called Exif data. This is where orientation information is stored. When viewing an image with the `img` tag or when using the CSS `background-image` property, Exif data is ignored.

The reason it works in Chrome directly is because they provided a [fix](https://code.google.com/p/chromium/issues/detail?id=56845#c66) for that particular scenario.

There is a [CSS property](http://caniuse.com/#feat=css-image-orientation) that would fix this, but unfortunately Chrome has not added support for it yet. So there doesn't appear to be any simple solution available to address this problem at this time.

**Comment by alanclayton** [comment]
Not going to fix.
