### ISSUE TITLE
Displays reporting 'image-load-error'

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/widget-image#208]
~4% of displays are not rendering their configured image and the error being reported is 'image-load-error'. We need to identify what cause this happen and apply corrections to eliminate problem from occurring.

**Comment by olegrise** [comment]
I looked at the logs and manually spot checked a number of URLs. The absolute majority of files that report the 'image-load-error' simply do not exist. I can think of two options for fixing this issue:

1. Log the message as a "warning" instead of "error"
2. Let a user know that there is a problem with their image so they can go and fit it

My vote is option # 2. It can be done in many different ways from sending email to in-app notifications. For that reason my recommendation is to start with requirements. 

@alanclayton please advise.

**Comment by alanclayton** [comment]
@olegrise don't we have another uptime error logged that is unique to a file not existing?

**Comment by olegrise** [comment]
@alanclayton I double checked the code - I don't see any other errors logged by the widget-image related to a file not existing.

**Comment by alanclayton** [comment]
Okay, thanks @olegrise I agree with your recommendation. This defect should remain open until we are informing the user and providing the correction.  @stulees FYI

**Comment by alanclayton** [comment]
https://github.com/Rise-Vision/widget-image/issues/223
