### ISSUE TITLE
Endpoints reporting 'rise storage error'

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/widget-image#210]
Endpoints unable to render their configured image and reporting rise storage error.

**Comment by alanclayton** [comment]
Defect opened by mistake.

**Comment by stulees** [comment]
@alanclayton The conclusion through investigation is that this error occurs because the endpoint that the presentation is running on has a firewall blocking some types of requests. Specifically in this case, the requests to domain `https://storage-dot-rvaserver2.appspot.com/` are blocked, which the rise-storage component requests to when running in shared schedule for obtaining file/folder metadata from GCS. 

Given this, what do you advise the behaviour of the Widget should be in this situation?

**Comment by alanclayton** [comment]
@stulees I think all files should be fetched from a risevision.com domain so we don't have to ask users to make so many firewall exceptions. And asking for access to appspot.com opens up a lot more than just our files which may not be easy for an end user to do.

**Comment by stulees** [comment]
@alanclayton As per our discussion today with @olegrise and Byron, we will look into the option of GCS url mapping and see if it's feasible. If so, we'll determine the rough scope of effort to first address the use of `https://storage-dot-rvaserver2.appspot.com/` from our Widgets requesting storage files as per this issue. Thanks

**Comment by alanclayton** [comment]
@stulees Thanks! We also need to inform the user and provide them with the correction. Thanks

**Comment by alanclayton** [comment]
Replaced with https://github.com/Rise-Vision/widget-image/issues/223
